export const TOOLTIP_DELAY = 200;
export const CTRL_TOOLTIP_DELAY = 1000;
export const MAX_ASSET_NAME_LENGTH = 50;
export const ASSET_MIN_CARDINALITY = 1; //default min cardinality for new asset
export const ASSET_MAX_CARDINALITY = 1; //default max cardinality for new asset
export const URI_PREFIX = "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/"
export const ASSET_DEFAULT_POPULATION = "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#PopLevelSingleton"
export const MODELLING_ERRORS_URI = "http://it-innovation.soton.ac.uk/ontologies/trustworthiness/domain#Anomalies";
export const MODEL_NAME_LIMIT = 50;
export const MODEL_DESCRIPTION_LIMIT = 500;
export const DISABLE_GROUPING = false; //disable add group feature on Canvas
