#An update query to remove and replace the given data, with the given property for a given uri
#Param 1, 2, 4, 5 the uri of the graph being updated
#Param 3 the data that is being inserted
#Param 6 is the uri of the class
#Param 7 is the property of the data being updated
DELETE{
	GRAPH<%s>{
		?uri ?t ?o .
	}
}INSERT{
	GRAPH<%s>{
		?uri ?t %s .
	}
}
USING <%s>
USING NAMED <%s>
WHERE{
	BIND(<%s> as ?uri)
	BIND(%s as ?t)
	OPTIONAL{
		?uri ?t ?o .
	}
}