name: Docker Image CI

on:
  push:
    branches: [ "dev",  "9-add-ci-support-for-building-docker-image" ]
  pull_request:
    branches: [ "dev",  "9-add-ci-support-for-building-docker-image" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: LFS checkout
      run: git lfs checkout

    - name: Build the Docker image
      run: |
        TIMESTAMP=$(git show -s --format=%cI ${GITHUB_SHA})
        SHORT_TIME=$(echo $TIMESTAMP | sed 's/[-:]//g')
        TAG=spyderisk/system-modeller:$(echo ${GITHUB_REF} | sed 's/.*\///')-${SHORT_TIME:0:13}
        docker build --tag ${TAG} --build-arg CI_COMMIT_SHA=${GITHUB_SHA} --build-arg CI_COMMIT_TIMESTAMP=${TIMESTAMP} --build-arg MAVEN_USER=${{ github.actor }} --build-arg MAVEN_PASS=${{ secrets.PACKAGE_READ_SECRET }} --file Dockerfile --target ssm-production "."

    - name: Push Docker image to registry
      run: | 
        docker login -u spyderisk -p ${{ secrets.DOCKER_HUB_RW_SECRET }}
        docker push ${TAG}
