name: Test and publish tag

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  #check-env:
  #  runs-on: ubuntu-22.04
  #  steps:
  #  - name: Check env
  #    run: |
  #      echo "${{github.event_name}}"
  #      echo "${{GITHUB_REF}}"

  publish-tag:

    # This job should only run if the test job succeeds
    # Don't run this job if it's a pull request, otherwise we get an image with branch name "merge" for every PR
    #needs: test
    #if: success() && github.event_name != 'pull_request'
    # Check if GITHUB_REF is a tag
    if: contains(GITHUB_REF, 'tags')
 
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Build the Docker image
      # The metadata inside the image will include the final git commit SHA and the time of the final commit.
      # The tag applied to the image will be like spyderisk/system-modeller:<branch-name>-<timestamp>
      # e.g. spyderisk/system-modeller:dev-20230405T1012
      # Where the timestamp is the time of the final commit in the build.
      # In addition, the image is tagged with spyderisk/system-modeller:<branch-name>-latest
      run: |
        echo "${{github.event_name}}"
        echo "${GITHUB_REF}"
        TAG_ROOT=spyderisk/system-modeller
        TIMESTAMP=$(git show -s --format=%cI ${GITHUB_SHA})
        SHORT_TIME=$(echo ${TIMESTAMP} | sed 's/[-:]//g')
        REF_END=$(echo ${GITHUB_REF} | sed 's/.*\///')
        TAG_DATE=${TAG_ROOT}:${REF_END}-${SHORT_TIME:0:13}
        TAG_LATEST=${TAG_ROOT}:${REF_END}-latest
        echo "TAG_DATE=${TAG_DATE}" >> ${GITHUB_ENV}
        echo "TAG_LATEST=${TAG_LATEST}" >> ${GITHUB_ENV}
        #docker build --tag ${TAG_DATE} --tag ${TAG_LATEST} --build-arg CI_COMMIT_SHA=${GITHUB_SHA} --build-arg CI_COMMIT_TIMESTAMP=${TIMESTAMP} --file Dockerfile --target ssm-production "."

    - name: Push Docker image to registry
      run: | 
        echo "docker login -u ${{ vars.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_RW_SECRET }}"
        echo "docker push ${TAG_DATE}"
        echo "docker push ${TAG_LATEST}"

